"""Revision ID: 0041e972f943
Revises: d9fb4ca12918
Create Date: 2024-02-19 21:38:06.024319.

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0041e972f943"
down_revision: Union[str, None] = "d9fb4ca12918"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("services", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("rooms_quantity", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("image_id", sa.Integer(), nullable=True))
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("image_id")
        batch_op.drop_column("rooms_quantity")
        batch_op.drop_column("services")
        batch_op.drop_column("location")

    # ### end Alembic commands ###
